### ISSUE TITLE
An umbrella issue for small bugs encountered

### ISSUE THREAD

**Issue by m4rrc0** [directus/next#283]
Hi, I landed on a few bugs while trying out `9.0.0-alpha.33`.
I am on Debian 10.
The purpose of this list is to discover easily reproducible bugs quickly. If you can't reproduce some of them quickly, please tell me and we can create a dedicated issue and dig deeper.

Note that I generated the projects with `npx create-directus-project`. The first issue choosing SQLite as DB, all the others with MySQL.

- A fresh project generated with SQLite just does not work
`INTERNAL_SERVER_ERROR: columnsPerTable.flat is not a function`

- After creating a collection with all 6 system fields and a title string, I can't create an item of that collection. The problematic fields are `date_created` and `date_updated` which give a code 500 in the console I think.

- Removing the `status` field from the data model, then returning to the list of items to edit them gives a code 500
``select `title`, `id` from `collectionname` where not `status` = 'archived' order by `id` asc limit 25 - ER_BAD_FIELD_ERROR: Unknown column 'status' in 'where clause'``

- When editing a data model, if I try to drag and drop fields to reorganize them, it does not work and the mouse becomes unresponsive in the UI until I refresh the page or change page by going back in the browser etc.

**Comment by benhaynes** [comment]
Thank you so much for this, @m4rrc0!! We haven't done much testing in SQLite (small team)... so this and the MySQL issues are greatly appreciated! We'll get right on this.

**Comment by rijkvanzanten** [comment]
@m4rrc0 for

> When editing a data model, if I try to drag and drop fields to reorganize them, it does not work and the mouse becomes unresponsive in the UI until I refresh the page or change page by going back in the browser etc.

What browser is this in?

**Comment by m4rrc0** [comment]
> What browser is this in?

Chrome.
Your comment made me try Firefox too. Drag and drop does not work but it doesn't kill the mouse.

And BTW, no error shows in the console.

**Comment by rijkvanzanten** [comment]
@m4rrc0 What version / OS? 

I'm not seeing any dnd related issues on Firefox 80.0.1 / Edge 85.0.564.44 / Safari 13.1.2 on macOS 10.15.6

**Comment by m4rrc0** [comment]
I am on Chrome OS running a VM with Debian 10. It shouldn't have any consequence on dnd as it is a purely client-side feature but that is why...
Chrome is version 84 in Chrome OS
Firefox is ESR version 68 in Debian 10
And I installed Midori (a WebKit browser) version 7 in Debian and it is the same result as Firefox, not crashing but not working.

You seem to be using `vuedraggable` for this, right?
The example [there](https://sortablejs.github.io/Vue.Draggable/#/simple) works fine for me in Chrome...

Is it possible `mousetrap` is interfering maybe?
Is there something I can test to help you out?

**Comment by benhaynes** [comment]
While not likely given that this is happening in multiple browsers for you, but might you have some browser extensions installed that could be conflicting? Unless we can get this issue confirmed by another user, it seems like it might be something specific to your configuration.

**Comment by shealavington** [comment]
![image](https://user-images.githubusercontent.com/16869302/93337688-5f9dae80-f821-11ea-9a10-ed0b3e369a66.png)

I installed a development version and have the same issue...

**Comment by rijkvanzanten** [comment]
I believe the 4 points in the OP are resolved. We can open new issues if any of them has a part 2

**Comment by m4rrc0** [comment]
Testing again with `9.0.0-beta.1`

A fresh SQLite project gives me the following on `npx directus start`:

```
11:59:32 💀 Can't connect to the database.
11:59:32 ⚠️  pino.final with prettyPrint does not support flushing
11:59:32 💀 connect ECONNREFUSED 127.0.0.1:3306 
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
    --------------------
    at Protocol._enqueue (/home/marcoet/code/tests/directus9-mysql/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/marcoet/code/tests/directus9-mysql/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/marcoet/code/tests/directus9-mysql/node_modules/mysql/lib/Connection.js:116:18)
    at /home/marcoet/code/tests/directus9-mysql/node_modules/knex/lib/dialects/mysql/index.js:69:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/home/marcoet/code/tests/directus9-mysql/node_modules/knex/lib/dialects/mysql/index.js:64:12)
    at create (/home/marcoet/code/tests/directus9-mysql/node_modules/knex/lib/client.js:291:39)
```

**Comment by m4rrc0** [comment]
Hey. I should be doing a lot more testing this weekend. If we are lucky I won't have to come back here though. ;)

The 3 first bugs are solved for me in `9.0.0-beta.1`.
SQLite seems to have other issues still but I won't be testing it thoroughly. From the quick look I had, it seems I was not able to delete a `status` field from a data model. That is about as far as I will be testing SQLite.

The drag and drop bug is still present for me obviously.
If it is indeed related to a specific setup, I understand it is not a priority to fix it but in the long run I can't be the only one to experience it. I would like to suggest an alternative way of moving things around. Having a 'move up' and 'move down' options in the '3 dots menu' of draggable fields would do the trick.

Note: I guess accessibility is not really in the current scope of development but I believe these options are also relevant in that context.

**Comment by benhaynes** [comment]
Accessibility is certainly on the list, but it a lower priority than stability at this point. We'll get there!

🔔  @kukulaka for testing deleting `status` field within SQLite (though this could be a global issue)

**Comment by m4rrc0** [comment]
I may have found a more reasonable reason for the dnd bug. I have a touch screen. And... dnd works perfectly with touch. I absolutely didn't think of trying it before today.

I have got another list of bugs for you. Let me just drop my list unedited. And tell me if we need to dig on certain points.

- [ ] duplicating fields does not work
- [ ] `"Add New Row" Label` and `Template` fields (in the repeater field at least) forbids entering a space character at the end of the value. We can add spaces in between words after having typed them in though.
- [ ] on medium size screen, when creating a field on a data model, on the 'interface' screen, after selecting an interface, opening the burger menu on the left -> the selected interface shows above the menu
![image](https://user-images.githubusercontent.com/16718691/94370446-56012a00-00f0-11eb-9d0e-80edc6c64312.png)

- [ ] Repeater: no more possibility to limit the number of occurrences.
In another project I was using it to format an address as JSON and limiting the number of entries to 1. Is there another way to create a structured JSON object with a decent user interface?
- [ ] no more map field to get coordinates
- [ ] I have found how to create a reference to a user but how to use it to make the user the owner of the entry and setup a role that allows them to edit only what is theirs? Is it just not ready yet but in the pipeline?
- [ ] couldn't assign a user to a role from the role form when creating a new one
- [ ] when user is disconnected from the app (in my case I changed the settings of a connected user to disallow app access), there is an option to "Switch account". It seems to log the user out but does not redirect to the login page
- [ ] I would like to show the id value of a model in the app because editors will need to read it to be able to use it in real life... does not seem possible
- [ ] `displays.color.color`, `displays.color.description`, `displays.labels.description` appear like this in the data model creation forms
- [ ] cannot deduce `slug` from another field?
- [ ] cannot 'generate and save' 2 UUIDs on the same model apparently?
- [ ] Cannot change the field used as primary key? And cannot delete the ID field...
- [ ] documentation about custom role access definition? Or is a more user friendly interface coming to edit role access?

**Comment by benhaynes** [comment]
Thank you @m4rrc0 — if at all possible, after this issue, could you open new bugs as individual tickets so we can add them to our workflow in a more organized manner?

**Comment by nickrum** [comment]
@m4rrc0 may I ask, did you update your directus installation to `v9.0.0-beta.2` before doing your latest round of testing?
Your issues with drag and drop sound very similar to #314 and the fix for that should be included in said version.

**Comment by m4rrc0** [comment]
> if at all possible, after this issue, could you open new bugs as individual tickets so we can add them to our workflow in a more organized manner?

@benhaynes I can try and see if I get discouraged.
To be clear, you will not mind having unconfirmed, half-baked bug reports or questions like some of the above in separate issues?

@nickrum unfortunately no. I started my last round of testing before beta 2 was out.
But I will probably start fresh from a new instance soon, maybe waiting a little for beta 3 or 4 to be available.

Note: I tried `npm update` to beta 2 yesterday but I guess the project is not ready for this yet. A field was missing on the user table and I did't go down the road of trying and update the DB manually because I didn't know if it would be a matter of 5 min or 5 hours.

**Comment by benhaynes** [comment]
Yeah! Always better to have them tracked as individual issues (even half-baked). 😄 

And migrations will be coming in the RC, then you can more reliably use `npm update`.

**Comment by rijkvanzanten** [comment]
I believe all actionable issues in the above list are fixed. Lets open new issues if anything else arises / still persists.

As for `npm update`, we don't include database migrations to migrate between versions in the alpha/beta releases. Like @benhaynes said, once we hit RC.1 we'll start including migrations so you can move your existing DB between versions
